Ds 1396 add register user endpoint
Contxt-Ltd/darkspark-example-expressjs pull request #1
Opened 2022-11-02 11:17 UTC by bahulneel

2022-11-03 14:46 UTC, robbobby commented on README.md
>  2. Skip the onboarding dialog and click "Take me to API keys". Or just go directly to [API Keys](https://darkspark.io/account/apikeys).
There is a pre step to this to navigate to the users default workspace.

2022-11-03 15:20 UTC, bahulneel commented on README.md
>  2. Skip the onboarding dialog and click "Take me to API keys". Or just go directly to [API Keys](https://darkspark.io/account/apikeys).
Can you suggest some text?

2022-11-03 15:26 UTC, neil-gall commented on README.md
>  2. Skip the onboarding dialog and click "Take me to API keys". Or just go directly to [API Keys](https://darkspark.io/account/apikeys).
```suggestion
2. Skip the onboarding dialog and navigate to Account / [API Keys](https://darkspark.io/account/apikeys).
```

2022-11-04 09:58 UTC, robbobby approved these changes

2022-11-04 09:59 UTC, rujames commented on index.mjs
> +// console.log(apiDoc['paths']['/users']['post']);
```suggestion
```

2022-11-04 10:06 UTC, robbobby requested changes

2022-11-04 10:06 UTC, robbobby commented on README.md
>  6. Run `npm start`
```suggestion
6. Run `npm install`
7. Run `npm start`
```

2022-11-04 10:06 UTC, rujames commented on .prettierrc
> +}
The files in this PR haven't been formatted in accordance with this Prettier configuration.  This should only be included if we intend to adhere to it.

2022-11-04 10:51 UTC, bahulneel commented on index.mjs
> +    // process.exit(1);
I didn't like that behaviour, I may want to check out the sample so before I get an API key

2022-11-04 11:14 UTC, rujames commented on index.mjs
> +    // process.exit(1);
```suggestion
```

2022-11-07 10:25 UTC, neil-gall approved these changes

2022-11-07 11:16 UTC, merged